#!/usr/bin/env python3
"""Entry point for the shape designer and its xArm tracing backend."""

import os
import sys

import rclpy
from ament_index_python.packages import get_package_share_directory
from rclpy.parameter import Parameter

from avatar_challenge.designer_server import DesignerServer
from avatar_challenge.shape_tracer_node import PlannerRejected, ShapeTracerNode


def runtime_config_path() -> str:
    """Where designs sent from the browser are kept.

    Deliberately not the installed package share directory: that is generated by
    colcon, may be read-only, and is overwritten by the next build.
    """
    root = os.environ.get("ROS_HOME") or os.path.join(
        os.path.expanduser("~"), ".ros")
    return os.path.join(root, "avatar_challenge", "designer_shapes.json")


def main(argv=None):
    rclpy.init(args=argv)
    node = None
    server = None
    try:
        share = get_package_share_directory("avatar_challenge")
        # The tracer requires a shapes file; the designer supplies shapes over
        # HTTP instead, so default the parameter rather than making every
        # `ros2 run` of this node pass one it will not use.
        node = ShapeTracerNode(parameter_overrides=[
            Parameter("shapes_file", Parameter.Type.STRING,
                      os.path.join(share, "config", "shapes.json")),
        ])
        node.declare_parameter("port", 8080)
        # Loopback by default: this moves a robot, and should not be reachable
        # from the network unless someone deliberately says so.
        node.declare_parameter("bind_address", "127.0.0.1")

        server = DesignerServer(
            node,
            page_path=os.path.join(share, "web", "shape_designer.html"),
            config_path=runtime_config_path(),
            port=node.get_parameter("port").value,
            bind_address=node.get_parameter("bind_address").value,
        )
        server.start()
        if node.home_on_start:
            node.get_logger().info("Moving to the ready pose")
            try:
                node.go_home()
            except PlannerRejected as exc:
                # The designer has nothing to trace yet, so a controller that is
                # slow to come up must not take the server down with it.
                node.get_logger().warn(
                    f"could not reach the ready pose at startup ({exc}); "
                    "serving anyway -- the next trace will retry")
        server.spin(rclpy)
    except (KeyboardInterrupt, SystemExit):
        pass
    except Exception as exc:  # noqa: BLE001
        if node is not None:
            node.get_logger().error(f"designer_server failed: {exc}")
        else:
            print(f"designer_server failed during startup: {exc}", file=sys.stderr)
        sys.exit(1)
    finally:
        if server is not None:
            server.stop()
        if node is not None:
            node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":
    main()
